### PR TITLE
Extend the functionality

### PR DESCRIPTION
**Pull request by jinlibao**
Hi Jiahao,

Thank you for creating this Chrome extension, which makes our lives so much easier. I very much appreciate it! This is a pull request to add some functionalities:

* Optimize strategy to locating cells of "payorId" and "Add Transaction"
* Add the functionality to find all the payorId's and validate the user-provided payorId
* Add the feature to import multiple 1099-B forms by adding payorId eventListener
* Update "getTotalProceeds" accordingly due to multiple 1099-B forms
* Increase the readability for HTML by using multi-line string
* Make UI more native by conforming the stylesheet provided Glacier Tax Prep
* Reorganize the instruction and add a disclaimer
* Fix whitespaces and fix the format of certain lines
* Fix the bug when loading the unpacked

Best,
Libao

### CODE REVIEW

**Comment by JiahaoShan** [comment]
Thanks for contributing, Libao : ) 

* Just a note. Since I no longer have access to the site, I am unable to verify this functionality. Merged with full trust. 

Thanks again for improving this to let it help others.

**Comment by jinlibao** [comment]
> Thanks for contributing, Libao : )
> 
> * Just a note. Since I no longer have access to the site, I am unable to verify this functionality. Merged with full trust.
> 
> Thanks again for improving this to let it help others.

Jiahao,

Thank you for your quick response and trust! I just noticed that the extension is no longer available on Chrome Web Store. I am wondering if it is possible that you can still publish the original version and let me publish the updated one which I can verify the functionality. That way, we can make both version available to users that can benefit more people (at least if the newer version doesn't work, they can still reply on the original version). What do you think?

Heads-up: a new pull request is coming soon! ;-)

**Comment by JiahaoShan** [comment]
@jinlibao Sorry for the late reply. Missing notification here. 

I have sent invite to you for being the collaborator for this repo and you have my written permission to publish this plugin freely using your platform account : ) 

Thanks again for contributing.

**Comment by jinlibao** [comment]
@JiahaoShan That's fine, no worries! And thank you for inviting me!

**Pull request merged**
